services:
  web:
    build: .
    container_name: flask_app
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    env_file:
      - .env
    restart: unless-stopped

  database:
    image: mysql:8.4
    container_name: mysql_server
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_storage:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 15s
      timeout: 10s
      retries: 3

volumes:
  mysql_storage:
